basePath: /api/test/v1/
definitions:
  models.Video:
    properties:
      duration:
        type: integer
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:2121
info:
  contact: {}
  description: API for managing videos.
  title: Video
  version: "1.0"
paths:
  /videos/create-video:
    post:
      description: Add New Video
      parameters:
      - description: Video Data
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/models.Video'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Success
          schema:
            type: string
      summary: Create Video
      tags:
      - Videos
  /videos/delete-video/{id}:
    post:
      description: Delete Video
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete Video
      tags:
      - Videos
  /videos/get-videos:
    get:
      description: Retrieve a list of videos from the database
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Success
          schema:
            type: string
      summary: Get all videos
      tags:
      - Videos
swagger: "2.0"
